#!/bin/bash
set -euo pipefail

# E.B.Smith, June 2017  -  Create a new git branch from the current branch and push it upstream.

branch_name="$1"
git checkout -b "$branch_name"
git push -u origin "$branch_name"
