#!/bin/bash
set -euo pipefail
IFS=$'\n'

# E.B. Smith, December 2016  -  Cleans up old dead git branches.

echo ">>> Pruning old branches..."
git fetch --prune
git checkout -q master

# Delete all the merged staging branches:
git branch --merged staging |
while read -r branch
do
    if [[ "$branch" = "* master"  ||
          "$branch" = "  qa"      ||
          "$branch" = "  staging" ||
          "$branch" = "  beta" ]]
    then
        continue
    fi
    branch=$(echo "$branch" | xargs)
    # echo ">>> Deleting merged branch '$branch'."
    git branch -d "$branch"
done

# Ask to delete all the remote-gone local branches:
while read -r -u 3 branch
do
    if [[ "$branch" = "* master"  ||
          "$branch" = "  qa"      ||
          "$branch" = "  staging" ||
          "$branch" = "  beta" ]]
    then
        continue
    fi
    branch=$(echo "$branch" | xargs)
    git checkout -q "$branch"
    status=$(git status --porcelain --branch)
    if [[ "$status" = *'[gone]' ]]
    then
        if askYN "Delete local branch '$branch' (upstream gone)?"
        then
            git checkout -q master
            # echo ">>> Deleting $branch. "
            git branch -D "$branch"
        fi
    fi
done 3< <(git branch --list)

git checkout -q master
