#!/bin/bash
git log --oneline --graph --all --decorate --abbrev-commit

# Also:
# https://stackoverflow.com/questions/2421011/output-of-git-branch-in-tree-like-fashion
#
# git config --global alias.lgb "log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset%n' --abbrev-commit --date=relative --branches"
#
# git lgb
