#!/bin/bash
set -euo pipefail
function show_usage() {
    cat <<USAGE
git-show-date

    Shows a git blob date.

Usage:      git-show-date [ -h ] | [ <blob> ]

    -h      Show this help and exit.
    <blob>  The git blob to show the date.

USAGE
}

function show_date() {
    local blob="$1"
    local pretty_blob
    pretty_blob="$(printf "%-25.25s" "$blob")"
    git show --pretty="tformat:%<(25)%ai $pretty_blob %<(20,trunc)%an %s" --quiet "$blob"
}

if (( $# == 0 ))
then
    show_date "$(git rev-parse --abbrev-ref HEAD)"
    exit 0
fi

if [ "$1" = "-h" ]
then
    show_usage
    exit 0
fi

while (( $# > 0 ))
do
    show_date "$1"
    shift
done
