#!/bin/bash
set -euo pipefail

# E.B.Smith, June 2017  -  Create a new git branch from the current branch and push it upstream.

if (( $# != 1 ))
then
    echo ">>> Error: One argument is expected, the name of the new branch." 1>&2
    exit 1
fi

branch_name="$1"
git checkout -b "$branch_name"
git push -u origin "$branch_name"
