#!/bin/bash
set -euo pipefail
function show_usage() {
    cat <<USAGE
git-show-date

    Shows a git blob date.

Usage:      git-show-date [ -h ] | [ <blob> ]

    -h      Show this help and exit.
    <blob>  The git blob to show the date.

USAGE
}

function show_date() {
    local blob="$1"
    git show --pretty="tformat:%ai    %an    %s" --quiet "$blob"
}

if (( $# == 0 ))
then
    show_date "."
    exit 0
fi

if [ "$1" = "-h" ]
then
    show_usage
    exit 0
fi

while (( $# > 0 ))
do
    show_date "$1"
    shift
done
