#!/bin/bash
set -euo pipefail

# E.B.Smith, June 2017  -  Delete a git branch locally and upstream.

if (( $# == 0 ))
then
    printf "Usage: git-branch-delete <branch-name> ...\n" 1>&2
    exit 0
fi

if  git show-ref --verify --quiet "refs/heads/main"
then
    git checkout main
elif git show-ref --verify --quiet "refs/heads/master"
then
    git checkout master
fi

while (( $# > 0 ))
do
    branch_name="$1"
    if [[ "$branch_name" == remotes/origin/* ]]
    then
        branch_name="${branch_name#remotes/origin/}"
    fi
    printf "Branch: %s\n" "$branch_name"
    if [[ "$branch_name" == "master" ]] || [[ "$branch_name" == "main" ]]
    then
        printf "Can't delete master or main branches." 1>&2
        exit 1
    fi
    (git push origin --delete "$branch_name" || true)
    (git branch -D "$branch_name" || true)
    shift
done
