#!/bin/bash
set -eu o pipefail

# git-pull-master
# EB Smith, June 2019

current_branch="$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)"
branch="master"
if [ -z "$(git branch --list $branch)" ]
then
    branch="main"
fi
if [ -z "$(git branch --list $branch)" ]
then
    echo 1>&2 ">>> Error: Can't find main/master."
    exit 1
fi
git checkout "$branch"
git pull origin "$branch"
git checkout "$current_branch"
