#!/bin/bash
set -euo pipefail

#   resolvepath  -  Resolve any sym links in a path.
#
#   Usage: resolvepath <pathname>
#
#   Returns:  A pathname without any sym links.
#
#   If there is an error the script exits code 1, else the resolved pathname is printed to
#   stdout and the script exits code 0.
#
#   E.B. Smith  -  December 2013

function absolute_path() {
    local pathname="${1:-.}"
    local filename=""
    local original_path
    original_path="$(pwd)"
    while ! cd "$pathname" 2>/dev/null
    do
        filename="$(basename "$pathname")"/"$filename"
        pathname="$(dirname "$pathname")"
    done
    pathname="$(pwd)"
    cd "$original_path" || true
    pathname="$pathname/$filename"
    pathname="${pathname%%/}"
    echo "$pathname"
}

absolute_path "${1:-.}"

exit 0

# Tests:

absolute_path /etc # /etc
absolute_path ~/Foo/foo.txt
absolute_path ~/Foo # works
absolute_path .
absolute_path ./
absolute_path ../
absolute_path ..
absolute_path /
absolute_path ~
absolute_path ~/
absolute_path ~/Documents
absolute_path /\"\ \'
absolute_path /etc/../etc/
absolute_path /private//etc/
absolute_path /private//
absolute_path //private # //private
absolute_path ./aa.txt
absolute_path aa.tar.gz
absolute_path .aa.txt
absolute_path /.DS_Store
absolute_path ~/Documents/Books/
absolute_path
